[SERVERINFO]

VERSION         =   MS.Release.2.0
PACKETVERSION   =   2024100800
CLIENTVERSION   =   JP.R7.983.01

#nome do server
NAME            =   Messenger Server
GUID            =   30201

PORT            =   30201
#em ip local nao funciona!
IP              =   127.0.0.1

MAXUSER         =   2001

PROPERTY        =   4096

[OPTION]

; 1 ON, 0 OFF
SAME_ID_LOGIN	=	0

;TTL = Time To Live, tempo em millisegundos para derrubar o player se ele n�o madar a resposta nesse tempo
; ou 0 para desativar
TTL = 0

ANTIBOTTTL = 10000

[LOG]
DIR 		= Log

[NORMAL_DB]
DBENGINE	=  MSSQL
DBIP		=  pangya
DBNAME		=  pangya
DBUSER		=  sa
DBPASS		=  @pangya
DBPORT		=  1433
DBLOG		=  0

[AUTHSERVER]

IP		= 127.0.0.1
PORT	= 5577
