-- V1 Pangya schema translated from SQL/bk-schema-mssql-complet2022.sql (C# reference).
-- Type mapping: NVARCHAR/VARCHAR(max)->TEXT, DATETIME/DATETIME2->TIMESTAMPTZ,
-- IDENTITY->GENERATED BY DEFAULT AS IDENTITY, TINYINT->SMALLINT, BIT->BOOLEAN,
-- UNIQUEIDENTIFIER->UUID, IMAGE/VARBINARY->BYTEA.
-- Stored procedures (502) are NOT ported: servers will use explicit Jdbi SQL.
-- Original column names are preserved (quoted) including spaces and punctuation.

CREATE SCHEMA IF NOT EXISTS pangya;

CREATE TABLE pangya.account (
    "ID" VARCHAR(25) NOT NULL,
    "UID" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "PASSWORD" VARCHAR(33) NOT NULL,
    "IDState" BIGINT NOT NULL,
    "LastLogonTime" TIMESTAMPTZ NULL,
    "BlockTime" INTEGER NOT NULL,
    "Logon" SMALLINT NOT NULL,
    "FIRST_LOGIN" SMALLINT NOT NULL,
    "RegDate" TIMESTAMPTZ NULL,
    "NICK" VARCHAR(50) NOT NULL,
    "FIRST_SET" SMALLINT NOT NULL,
    "Guild_UID" INTEGER NOT NULL,
    "Sex" SMALLINT NOT NULL,
    "doTutorial" SMALLINT NOT NULL,
    "NomeCompleto" VARCHAR(50) NULL,
    "BirthDay" TIMESTAMPTZ NULL,
    "UserName" VARCHAR(23) NULL,
    "UserIp" VARCHAR(20) NULL,
    "ServerID" VARCHAR(20) NULL,
    game_server_id VARCHAR(20) NULL,
    "LastLeaveTime" TIMESTAMPTZ NULL,
    "LogonCount" BIGINT NOT NULL,
    "BlockRegDate" TIMESTAMPTZ NULL,
    "School" INTEGER NOT NULL,
    capability INTEGER NOT NULL,
    "Event" SMALLINT NOT NULL,
    "MannerFlag" SMALLINT NOT NULL,
    "Event1" SMALLINT NOT NULL,
    "Event2" INTEGER NOT NULL,
    domainid INTEGER NOT NULL,
    "ChannelFlag" SMALLINT NOT NULL,
    change_nick TIMESTAMPTZ NULL,
    "Question" VARCHAR(50) NULL,
    "Answer" VARCHAR(50) NULL,
    "MacAddress" VARCHAR(50) NULL,
    "Invited" BOOLEAN NULL,
    "Inviter_UID" INTEGER NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.achievements (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    tipo SMALLINT NOT NULL,
    "option" SMALLINT NOT NULL,
    quest_typeid INTEGER NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.authkey_game (
    "UID" INTEGER NOT NULL,
    "AuthKey" VARCHAR(8) NULL,
    "ServerID" INTEGER NOT NULL,
    valid SMALLINT NOT NULL
);

CREATE TABLE pangya.authkey_login (
    "UID" INTEGER NOT NULL,
    "AuthKey" VARCHAR(8) NOT NULL,
    valid SMALLINT NOT NULL
);

CREATE TABLE pangya.contas_beta (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    "NomeCompleto" VARCHAR(100) NOT NULL,
    "Birthday" TIMESTAMPTZ NULL,
    "Email" VARCHAR(100) NOT NULL,
    "Sexo" SMALLINT NOT NULL,
    "Pergunta" VARCHAR(100) NOT NULL,
    "Resposta" VARCHAR(120) NULL,
    "LoginID" VARCHAR(25) NOT NULL,
    "Senha" VARCHAR(33) NOT NULL,
    key_uniq UUID NOT NULL,
    finish_reg SMALLINT NOT NULL,
    date_reg TIMESTAMPTZ NULL,
    ip_register CHAR(20) NOT NULL,
    codigo CHAR(13) NULL,
    referrer_code CHAR(25) NULL,
    status_referal CHAR(10) NULL,
    "Invited" BOOLEAN NULL,
    "Inviter_UID" INTEGER NULL,
    recovery_expires TIMESTAMPTZ NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.counter_items (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_1st_anniversary (
    "EVENT_DONE" SMALLINT NOT NULL,
    "ALL_PLAYER_APT" BIGINT NOT NULL,
    "ALL_PLAYER_WIN" BIGINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("EVENT_DONE")
);

CREATE TABLE pangya.pangya_1st_anniversary_player_win_cp (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "LOGIN_DAYS" INTEGER NOT NULL,
    "COOKIE_POINT" BIGINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_achievement (
    "ID_ACHIEVEMENT" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "Nome" VARCHAR(100) NULL,
    "TypeID" INTEGER NOT NULL,
    active INTEGER NOT NULL,
    status INTEGER NOT NULL,
    PRIMARY KEY ("ID_ACHIEVEMENT")
);

CREATE TABLE pangya.pangya_approach_missions (
    numero BIGINT NOT NULL,
    tipo INTEGER NOT NULL,
    reward_tipo INTEGER NOT NULL,
    box INTEGER NOT NULL,
    flag INTEGER NOT NULL,
    active SMALLINT NOT NULL,
    PRIMARY KEY (numero)
);

CREATE TABLE pangya.pangya_assistente (
    "UID" INTEGER NOT NULL,
    "Assist" INTEGER NOT NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.pangya_attendance_reward (
    "UID" INTEGER NOT NULL,
    counter INTEGER NOT NULL,
    item_typeid_now INTEGER NOT NULL,
    item_qntd_now INTEGER NOT NULL,
    item_typeid_after INTEGER NOT NULL,
    item_qntd_after INTEGER NOT NULL,
    last_login TIMESTAMPTZ NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.pangya_attendance_table_item_reward (
    idx INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(50) NULL,
    typeid INTEGER NOT NULL,
    quantidade INTEGER NOT NULL,
    tipo INTEGER NOT NULL,
    PRIMARY KEY (idx)
);

CREATE TABLE pangya.pangya_auth_key (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Server_UID" INTEGER NULL,
    "key" CHAR(16) NULL,
    valid SMALLINT NULL
);

CREATE TABLE pangya.pangya_bot_gm_event_reward (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    qntd_time INTEGER NOT NULL,
    rate INTEGER NOT NULL,
    valid SMALLINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_bot_gm_event_time (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inicio_time TIME NOT NULL,
    fim_time TIME NOT NULL,
    channel_id SMALLINT NOT NULL,
    valid SMALLINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_caddie_information (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    parts_typeid INTEGER NOT NULL,
    gift_flag SMALLINT NOT NULL,
    "cLevel" SMALLINT NOT NULL,
    "Exp" INTEGER NOT NULL,
    "RegDate" TIMESTAMPTZ NOT NULL,
    "Period" SMALLINT NOT NULL,
    "EndDate" TIMESTAMPTZ NULL,
    "RentFlag" SMALLINT NOT NULL,
    "Purchase" SMALLINT NOT NULL,
    "parts_EndDate" TIMESTAMPTZ NULL,
    "CheckEnd" SMALLINT NOT NULL,
    "Valid" SMALLINT NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE pangya.pangya_card (
    card_itemid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    card_typeid INTEGER NOT NULL,
    "QNTD" INTEGER NULL,
    "GET_DT" TIMESTAMPTZ NULL,
    "USE_DT" TIMESTAMPTZ NULL,
    "END_DT" TIMESTAMPTZ NULL,
    "Slot" INTEGER NOT NULL,
    "Efeito" INTEGER NOT NULL,
    "Efeito_Qntd" INTEGER NOT NULL,
    card_type SMALLINT NOT NULL,
    "USE_YN" CHAR(1) NULL,
    PRIMARY KEY (card_itemid)
);

CREATE TABLE pangya.pangya_card_equip (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    parts_id INTEGER NOT NULL,
    parts_typeid INTEGER NOT NULL,
    card_typeid INTEGER NOT NULL,
    "Efeito" INTEGER NOT NULL,
    "Efeito_Qntd" INTEGER NOT NULL,
    "Slot" INTEGER NOT NULL,
    "USE_DT" TIMESTAMPTZ NULL,
    "END_DT" TIMESTAMPTZ NULL,
    "Tipo" INTEGER NOT NULL,
    "USE_YN" SMALLINT NOT NULL,
    date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_change_email_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    email_old VARCHAR(100) NOT NULL,
    email_new VARCHAR(100) NOT NULL,
    change_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_change_nickname_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    change_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_change_pwd_log (
    uid INTEGER NOT NULL,
    last_change TIMESTAMPTZ NOT NULL,
    change_date TIMESTAMPTZ NOT NULL,
    count INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_character_information (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    "UID" INTEGER NOT NULL,
    parts_1 INTEGER NOT NULL,
    parts_2 INTEGER NOT NULL,
    parts_3 INTEGER NOT NULL,
    parts_4 INTEGER NOT NULL,
    parts_5 INTEGER NOT NULL,
    parts_6 INTEGER NOT NULL,
    parts_7 INTEGER NOT NULL,
    parts_8 INTEGER NOT NULL,
    parts_9 INTEGER NOT NULL,
    parts_10 INTEGER NOT NULL,
    parts_11 INTEGER NOT NULL,
    parts_12 INTEGER NOT NULL,
    parts_13 INTEGER NOT NULL,
    parts_14 INTEGER NOT NULL,
    parts_15 INTEGER NOT NULL,
    parts_16 INTEGER NOT NULL,
    parts_17 INTEGER NOT NULL,
    parts_18 INTEGER NOT NULL,
    parts_19 INTEGER NOT NULL,
    parts_20 INTEGER NOT NULL,
    parts_21 INTEGER NOT NULL,
    parts_22 INTEGER NOT NULL,
    parts_23 INTEGER NOT NULL,
    parts_24 INTEGER NOT NULL,
    default_hair SMALLINT NOT NULL,
    default_shirts SMALLINT NOT NULL,
    gift_flag SMALLINT NOT NULL,
    "PCL0" SMALLINT NOT NULL,
    "PCL1" SMALLINT NOT NULL,
    "PCL2" SMALLINT NOT NULL,
    "PCL3" SMALLINT NOT NULL,
    "PCL4" SMALLINT NOT NULL,
    "Purchase" SMALLINT NOT NULL,
    auxparts_1 INTEGER NOT NULL,
    auxparts_2 INTEGER NOT NULL,
    auxparts_3 INTEGER NOT NULL,
    auxparts_4 INTEGER NOT NULL,
    auxparts_5 INTEGER NOT NULL,
    "CutIn_1" INTEGER NOT NULL,
    "CutIn_2" INTEGER NOT NULL,
    "CutIn_3" INTEGER NOT NULL,
    "CutIn_4" INTEGER NOT NULL,
    "Mastery" INTEGER NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE pangya.pangya_character_part_padrao (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    char_typeid INTEGER NOT NULL,
    parts_1 INTEGER NOT NULL,
    parts_2 INTEGER NOT NULL,
    parts_3 INTEGER NOT NULL,
    parts_4 INTEGER NOT NULL,
    parts_5 INTEGER NOT NULL,
    parts_6 INTEGER NOT NULL,
    parts_7 INTEGER NOT NULL,
    parts_8 INTEGER NOT NULL,
    parts_9 INTEGER NOT NULL,
    parts_10 INTEGER NOT NULL,
    parts_11 INTEGER NOT NULL,
    parts_12 INTEGER NOT NULL,
    parts_13 INTEGER NOT NULL,
    parts_14 INTEGER NOT NULL,
    parts_15 INTEGER NOT NULL,
    parts_16 INTEGER NOT NULL,
    parts_17 INTEGER NOT NULL,
    parts_18 INTEGER NOT NULL,
    parts_19 INTEGER NOT NULL,
    parts_20 INTEGER NOT NULL,
    parts_21 INTEGER NOT NULL,
    parts_22 INTEGER NOT NULL,
    parts_23 INTEGER NOT NULL,
    parts_24 INTEGER NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_clubset_enchant (
    uid INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    pang BIGINT NOT NULL,
    c0 SMALLINT NOT NULL,
    c1 SMALLINT NOT NULL,
    c2 SMALLINT NOT NULL,
    c3 SMALLINT NOT NULL,
    c4 SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_coin_cube_info (
    course_id SMALLINT NOT NULL,
    active SMALLINT NOT NULL,
    update_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_coin_cube_location (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course SMALLINT NOT NULL,
    hole SMALLINT NOT NULL,
    tipo SMALLINT NOT NULL,
    tipo_location SMALLINT NOT NULL,
    rate BIGINT NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    z DOUBLE PRECISION NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_comet_refill (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    min SMALLINT NOT NULL,
    max SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_command (
    idx BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    command_id INTEGER NOT NULL,
    arg1 INTEGER NOT NULL,
    arg2 INTEGER NOT NULL,
    arg3 INTEGER NOT NULL,
    arg4 INTEGER NOT NULL,
    arg5 INTEGER NOT NULL,
    target INTEGER NOT NULL,
    "regDate" TIMESTAMPTZ NOT NULL,
    "reserveDate" TIMESTAMPTZ NULL,
    flag SMALLINT NOT NULL,
    valid SMALLINT NOT NULL,
    PRIMARY KEY (idx)
);

CREATE TABLE pangya.pangya_command_gm_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    command_type INTEGER NOT NULL,
    gm_uid INTEGER NOT NULL,
    gm_nick VARCHAR(120) NOT NULL,
    capability BIGINT NOT NULL,
    nick_gift VARCHAR(120) NOT NULL,
    uid_gift INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_config (
    "UID" INTEGER NOT NULL,
    "GrandZodiacEventTime" SMALLINT NOT NULL,
    "ScratchyPorPointRate" SMALLINT NOT NULL,
    "PapelShopRareItemRate" SMALLINT NOT NULL,
    "PapelShopCookieItemRate" SMALLINT NOT NULL,
    "TreasureRate" SMALLINT NOT NULL,
    "PangRate" SMALLINT NOT NULL,
    "ExpRate" SMALLINT NOT NULL,
    "ClubMasteryRate" SMALLINT NOT NULL,
    "ChuvaRate" SMALLINT NOT NULL,
    "MemorialShopRate" SMALLINT NOT NULL,
    "AngelEvent" SMALLINT NOT NULL,
    "GrandPrixEvent" SMALLINT NOT NULL,
    "GoldenTimeEvent" SMALLINT NOT NULL,
    "LoginRewardEvent" SMALLINT NOT NULL,
    "BotGMEvent" SMALLINT NOT NULL,
    "SmartCalculator" SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_cookie_point_item_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cp_id_log BIGINT NULL,
    typeid INTEGER NULL,
    qnty INTEGER NULL,
    price BIGINT NULL
);

CREATE TABLE pangya.pangya_cookie_point_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NULL,
    "type" SMALLINT NULL,
    mail_id INTEGER NULL,
    cookie BIGINT NULL,
    item_qnty INTEGER NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_counter_item (
    "Count_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "TypeID" INTEGER NOT NULL,
    active INTEGER NOT NULL,
    "Count_Num_Item" INTEGER NOT NULL,
    PRIMARY KEY ("Count_ID")
);

CREATE TABLE pangya.pangya_coupon_desconto (
    "Nome" VARCHAR(50) NOT NULL,
    typeid INTEGER NOT NULL,
    valor INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_course_reward_treasure (
    "COURSE" SMALLINT NOT NULL,
    "PANGREWARD" INTEGER NOT NULL,
    PRIMARY KEY ("COURSE")
);

CREATE TABLE pangya.pangya_daily_quest (
    achieve_quest_1 INTEGER NOT NULL,
    achieve_quest_2 INTEGER NOT NULL,
    achieve_quest_3 INTEGER NOT NULL,
    "Reg_Date" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_daily_quest_player (
    uid BIGINT NOT NULL,
    last_quest_accept TIMESTAMPTZ NULL,
    today_quest TIMESTAMPTZ NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE pangya.pangya_dolfini_locker (
    uid INTEGER NOT NULL,
    senha VARCHAR(5) NULL,
    pang BIGINT NOT NULL,
    locker SMALLINT NOT NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE pangya.pangya_dolfini_locker_item (
    idx BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    flag SMALLINT NOT NULL,
    PRIMARY KEY (idx)
);

CREATE TABLE pangya.pangya_donation_epin (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    donation_id BIGINT NOT NULL,
    uid INTEGER NOT NULL,
    epin UUID NOT NULL,
    qntd BIGINT NOT NULL,
    retrive_uid INTEGER NULL,
    valid SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_donation_item_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    donation_id BIGINT NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_donation_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ADM_uid" INTEGER NOT NULL,
    uid INTEGER NOT NULL,
    plataforma SMALLINT NOT NULL,
    cash INTEGER NOT NULL,
    cookie_point INTEGER NOT NULL,
    email VARCHAR(100) NULL,
    obs VARCHAR(500) NULL,
    red_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_donation_new (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    plataforma SMALLINT NOT NULL,
    email VARCHAR(200) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    update TIMESTAMPTZ NULL,
    code VARCHAR(50) NOT NULL,
    "type" SMALLINT NOT NULL,
    status SMALLINT NOT NULL,
    reference VARCHAR(200) NOT NULL,
    gross_amount DOUBLE PRECISION NOT NULL,
    net_amount DOUBLE PRECISION NOT NULL,
    escrow TIMESTAMPTZ NULL,
    epin_id BIGINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_event_itens_site (
    "ITEM_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "EVENTO_ID" INTEGER NOT NULL,
    "NOME_ITEM" VARCHAR(255) NULL,
    "QNT_JOGADA" INTEGER NOT NULL,
    "TYPEID" INTEGER NOT NULL,
    "QNT_ITEM" INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_event_site (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "NOME_EVENTO" VARCHAR(255) NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL,
    "TIPO_EVENTO" VARCHAR(50) NOT NULL,
    "DATA_INICIAL" TIMESTAMPTZ NOT NULL,
    "DATA_FIM" TIMESTAMPTZ NOT NULL,
    "DATA_REGISTRO" TIMESTAMPTZ NULL,
    "ITENS" BOOLEAN NOT NULL
);

CREATE TABLE pangya.pangya_exception_log (
    "ExceptionID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NULL,
    "Username" VARCHAR(50) NULL,
    "ExceptionMessage" VARCHAR(2000) NULL,
    "Server" VARCHAR(50) NULL,
    "CreateDate" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_fast_pass_event (
    "UID" INTEGER NOT NULL,
    "HOLES_INIT" SMALLINT NOT NULL,
    "HOLES_COUNTER" BIGINT NOT NULL,
    "END_DATE" TIMESTAMPTZ NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_friend_list (
    uid INTEGER NOT NULL,
    uid_friend INTEGER NOT NULL,
    apelido VARCHAR(15) NOT NULL,
    unknown1 INTEGER NOT NULL,
    unknown2 INTEGER NOT NULL,
    unknown3 INTEGER NOT NULL,
    unknown4 INTEGER NOT NULL,
    unknown5 INTEGER NOT NULL,
    unknown6 INTEGER NOT NULL,
    flag1 SMALLINT NOT NULL,
    state_flag SMALLINT NOT NULL,
    flag5 SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_gacha (
    "index" INTEGER NOT NULL,
    townno INTEGER NOT NULL,
    charno INTEGER NOT NULL,
    shop INTEGER NOT NULL,
    numero INTEGER NOT NULL,
    coin INTEGER NOT NULL,
    rate INTEGER NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_gacha_coin (
    "index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    preco INTEGER NOT NULL,
    tipo SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_gacha_items (
    "index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gacha_num INTEGER NOT NULL,
    nome VARCHAR(50) NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    tipo SMALLINT NOT NULL,
    premio SMALLINT NOT NULL,
    secret SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_gacha_jp_all_item_list (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    char_type SMALLINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_gacha_jp_item_list (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active SMALLINT NOT NULL,
    gacha_num INTEGER NOT NULL,
    typeid_1 INTEGER NOT NULL,
    typeid_2 INTEGER NULL,
    qnty_1 BIGINT NOT NULL,
    qnty_2 BIGINT NULL,
    rarity_type SMALLINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_gacha_jp_player_win (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    gacha_num INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    qnty BIGINT NOT NULL,
    rarity_type SMALLINT NOT NULL,
    send_mail SMALLINT NOT NULL,
    valid SMALLINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_gacha_jp_rate (
    gacha_num INTEGER NOT NULL,
    rate_rare INTEGER NOT NULL,
    rate_normal INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_gift_table (
    "UID" INTEGER NOT NULL,
    "Msg_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Flag" SMALLINT NOT NULL,
    fromid VARCHAR(30) NOT NULL,
    message VARCHAR(500) NOT NULL,
    giftdate TIMESTAMPTZ NOT NULL,
    enddate TIMESTAMPTZ NULL,
    "Contador_Vista" INTEGER NOT NULL,
    "Lida_YN" SMALLINT NOT NULL,
    valid SMALLINT NOT NULL,
    PRIMARY KEY ("Msg_ID")
);

CREATE TABLE pangya.pangya_gm_gift_web_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GM_UID" INTEGER NOT NULL,
    "PLAYER_UID" INTEGER NOT NULL,
    "MSG_ID" INTEGER NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_golden_time_info (
    "index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" SMALLINT NOT NULL,
    begin DATE NOT NULL,
    "end" DATE NULL,
    rate INTEGER NOT NULL,
    is_end SMALLINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_golden_time_item (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    golden_time_id BIGINT NOT NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    qntd_time INTEGER NOT NULL,
    rate INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_golden_time_round (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    golden_time_id BIGINT NOT NULL,
    "time" TIME NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_grand_zodiac_pontos (
    uid INTEGER NOT NULL,
    pontos BIGINT NOT NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE pangya.pangya_grand_zodiac_times (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inicio_time TIME NOT NULL,
    fim_time TIME NOT NULL,
    "type" SMALLINT NOT NULL,
    valid SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_grandprix_clear (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    flag INTEGER NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_grandprix_event_config (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flag INTEGER NOT NULL,
    "Active" SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_guild (
    "GUILD_UID" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GUILD_ID" VARCHAR(8) NOT NULL,
    "GUILD_NAME" VARCHAR(50) NOT NULL,
    "GUILD_LEADER" INTEGER NOT NULL,
    "GUILD_SUB_MASTER" INTEGER NOT NULL,
    "GUILD_CONDITION_LEVEL" SMALLINT NOT NULL,
    "GUILD_STATE" SMALLINT NOT NULL,
    "GUILD_FLAG" SMALLINT NOT NULL,
    "GUILD_PERMITION_JOIN" SMALLINT NOT NULL,
    "GUILD_PANG" BIGINT NOT NULL,
    "GUILD_POINT" BIGINT NOT NULL,
    "GUILD_WIN" INTEGER NOT NULL,
    "GUILD_LOSE" INTEGER NOT NULL,
    "GUILD_DRAW" INTEGER NOT NULL,
    "GUILD_MARK_IMG" VARCHAR(12) NOT NULL,
    "GUILD_MARK_IMG_IDX" INTEGER NOT NULL,
    "GUILD_NEW_MARK_IDX" INTEGER NOT NULL,
    "GUILD_INTRO_IMG" VARCHAR(50) NULL,
    "GUILD_NOTICE" VARCHAR(110) NOT NULL,
    "GUILD_INFO" VARCHAR(110) NOT NULL,
    "GUILD_REG_DATE" TIMESTAMPTZ NOT NULL,
    "GUILD_ACCEPT_DATE" TIMESTAMPTZ NULL,
    "GUILD_CLOSURE_DATE" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_guild_atividade_player (
    "IDX" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "GUILD_UID" INTEGER NOT NULL,
    "FLAG" INTEGER NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_bbs (
    "SEQ" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OWNER_UID" INTEGER NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "TEXT" VARCHAR(500) NOT NULL,
    "TYPE" SMALLINT NOT NULL,
    "STATE" SMALLINT NOT NULL,
    "VIEWS" BIGINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_bbs_res (
    "SEQ" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BBS_SEQ" BIGINT NOT NULL,
    "OWNER_UID" INTEGER NOT NULL,
    "TEXT" VARCHAR(500) NOT NULL,
    "STATE" SMALLINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_intro_img_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    intro_img VARCHAR(50) NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_mark_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mark_idx INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_match (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guild_1_uid INTEGER NOT NULL,
    guild_2_uid INTEGER NOT NULL,
    guild_1_point INTEGER NOT NULL,
    guild_2_point INTEGER NOT NULL,
    guild_1_pang INTEGER NOT NULL,
    guild_2_pang INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_member (
    "GUILD_UID" INTEGER NOT NULL,
    "MEMBER_UID" INTEGER NOT NULL,
    "MEMBER_MSG" VARCHAR(64) NULL,
    "GUILD_PANG" INTEGER NOT NULL,
    "GUILD_POINT" INTEGER NOT NULL,
    "MEMBER_FLAG" INTEGER NOT NULL,
    "MEMBER_STATE_FLAG" INTEGER NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_notice (
    "SEQ" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GUILD_UID" INTEGER NOT NULL,
    "OWNER_UID" INTEGER NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "TEXT" VARCHAR(500) NOT NULL,
    "STATE" SMALLINT NOT NULL,
    "VIEWS" BIGINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_private_bbs (
    "SEQ" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GUILD_UID" INTEGER NOT NULL,
    "OWNER_UID" INTEGER NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "TEXT" VARCHAR(500) NOT NULL,
    "VIEWS" BIGINT NOT NULL,
    "STATE" SMALLINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_guild_private_bbs_res (
    "SEQ" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GUILD_BBS_SEQ" BIGINT NOT NULL,
    "OWNER_UID" INTEGER NOT NULL,
    "TEXT" VARCHAR(500) NOT NULL,
    "STATE" SMALLINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_guild_ranking (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GUILD_UID" INTEGER NOT NULL,
    "RANK" INTEGER NOT NULL,
    "LAST_RANK" INTEGER NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_guild_update_activity (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GUILD_UID" INTEGER NOT NULL,
    "OWNER_UPDATE" INTEGER NOT NULL,
    "PLAYER_UID" INTEGER NOT NULL,
    "TYPE_UPDATE" SMALLINT NOT NULL,
    "STATE" SMALLINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_gz_event_2016121600_rare_win (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    item_typeid INTEGER NULL,
    win_date TIMESTAMPTZ NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_hio_event (
    "INDEX" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "START_HIOS" INTEGER NOT NULL,
    "PROCESS_HIOS" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "FINISH_DATE" TIMESTAMPTZ NULL,
    PRIMARY KEY ("INDEX")
);

CREATE TABLE pangya.pangya_hio_event_items (
    "IDX" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "HIO_COUNT" INTEGER NOT NULL,
    "ITEM_NAME" VARCHAR(50) NULL,
    "ITEM_TYPEID" INTEGER NOT NULL,
    "ITEM_QNTD" INTEGER NOT NULL,
    "ITEM_QNTD_TIME" INTEGER NOT NULL,
    "EVENT_DESCRIPTION" VARCHAR(255) NULL,
    "END_EVENT" TIMESTAMPTZ NULL,
    "REG_DATE" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_hio_event_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    hio_count INTEGER NOT NULL,
    received_at TIMESTAMPTZ NULL,
    status INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_hole_event (
    "INDEX" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "START_HOLES" INTEGER NOT NULL,
    "PROCESS_HOLES" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "FINISH_DATE" TIMESTAMPTZ NULL,
    PRIMARY KEY ("INDEX")
);

CREATE TABLE pangya.pangya_hole_event_config (
    "EVENT_ID" INTEGER NULL,
    "START_EVENT" TIMESTAMPTZ NOT NULL,
    "END_EVENT" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_hole_event_items (
    "EVENT_ID" INTEGER NULL,
    "HOLE_COUNT" INTEGER NOT NULL,
    "ITEM_NAME" VARCHAR(50) NULL,
    "ITEM_TYPEID" INTEGER NOT NULL,
    "ITEM_QNTD" INTEGER NOT NULL,
    "ITEM_QNTD_TIME" INTEGER NOT NULL,
    "EVENT_DESCRIPTION" VARCHAR(255) NULL
);

CREATE TABLE pangya.pangya_ip_table (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip VARCHAR(40) NOT NULL,
    mask VARCHAR(18) NOT NULL,
    date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_item_buff (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    tipo SMALLINT NOT NULL,
    percent INTEGER NOT NULL,
    use_yn SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_item_buy_shop_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_time INTEGER NOT NULL,
    item_type INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL,
    item_pang BIGINT NOT NULL,
    item_cookie BIGINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_item_mail (
    "Msg_ID" INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    "Flag" SMALLINT NOT NULL,
    "GET_DATE" TIMESTAMPTZ NULL,
    "Quantidade_item" INTEGER NOT NULL,
    "Quantidade_Dia" INTEGER NOT NULL,
    "Pang" BIGINT NOT NULL,
    "Cookie" BIGINT NOT NULL,
    "GM_ID" INTEGER NOT NULL,
    "Flag_Gift" INTEGER NOT NULL,
    "UCC_IMG_MARK" VARCHAR(12) NOT NULL,
    "Type" SMALLINT NOT NULL,
    valid SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_item_warehouse (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    valid SMALLINT NOT NULL,
    regdate TIMESTAMPTZ NULL,
    "Gift_flag" SMALLINT NOT NULL,
    flag SMALLINT NOT NULL,
    "Applytime" TIMESTAMPTZ NULL,
    "EndDate" TIMESTAMPTZ NULL,
    "C0" SMALLINT NOT NULL,
    "C1" SMALLINT NOT NULL,
    "C2" SMALLINT NOT NULL,
    "C3" SMALLINT NOT NULL,
    "C4" SMALLINT NOT NULL,
    "Purchase" SMALLINT NOT NULL,
    "ItemType" SMALLINT NOT NULL,
    "ClubSet_WorkShop_Flag" SMALLINT NOT NULL,
    "ClubSet_WorkShop_C0" SMALLINT NOT NULL,
    "ClubSet_WorkShop_C1" SMALLINT NOT NULL,
    "ClubSet_WorkShop_C2" SMALLINT NOT NULL,
    "ClubSet_WorkShop_C3" SMALLINT NOT NULL,
    "ClubSet_WorkShop_C4" SMALLINT NOT NULL,
    "Mastery_Pts" INTEGER NOT NULL,
    "Recovery_Pts" INTEGER NOT NULL,
    "Level" INTEGER NOT NULL,
    "Up" INTEGER NOT NULL,
    "Total_Mastery_Pts" BIGINT NOT NULL,
    "Mastery_Gasto" INTEGER NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE pangya.pangya_last_players_user (
    "UID" INTEGER NOT NULL,
    "SEX_0" INTEGER NULL,
    "ID_0" VARCHAR(22) NULL,
    "NICK_0" VARCHAR(22) NULL,
    "UID_0" INTEGER NULL,
    "SEX_1" INTEGER NULL,
    "ID_1" VARCHAR(22) NULL,
    "NICK_1" VARCHAR(22) NULL,
    "UID_1" INTEGER NULL,
    "SEX_2" INTEGER NULL,
    "ID_2" VARCHAR(22) NULL,
    "NICK_2" VARCHAR(22) NULL,
    "UID_2" INTEGER NULL,
    "SEX_3" INTEGER NULL,
    "ID_3" VARCHAR(22) NULL,
    "NICK_3" VARCHAR(22) NULL,
    "UID_3" INTEGER NULL,
    "SEX_4" INTEGER NULL,
    "ID_4" VARCHAR(22) NULL,
    "NICK_4" VARCHAR(22) NULL,
    "UID_4" INTEGER NULL
);

CREATE TABLE pangya.pangya_last_up_clubset (
    item_id INTEGER NOT NULL,
    "UID" INTEGER NOT NULL,
    "State" SMALLINT NOT NULL,
    item_usado INTEGER NOT NULL,
    "Quantidade" INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_login_reward (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "type" SMALLINT NOT NULL,
    days_to_gift INTEGER NOT NULL,
    n_times_gift INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL,
    item_qntd_time INTEGER NOT NULL,
    is_end SMALLINT NOT NULL,
    end_date TIMESTAMPTZ NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_login_reward_player (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login_reward_id BIGINT NOT NULL,
    uid INTEGER NOT NULL,
    count_days INTEGER NOT NULL,
    count_seq INTEGER NOT NULL,
    is_clear SMALLINT NOT NULL,
    update_date TIMESTAMPTZ NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_lucia_attendance (
    "UID" INTEGER NOT NULL,
    count_day BIGINT NOT NULL,
    last_day_attendance TIMESTAMPTZ NULL,
    last_day_get_item TIMESTAMPTZ NULL,
    try_hacking_count INTEGER NOT NULL,
    block_type SMALLINT NOT NULL,
    block_end_date TIMESTAMPTZ NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.pangya_lucia_attendance_reward_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "MSG_ID" INTEGER NOT NULL,
    "ERROR" VARCHAR(50) NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_mac_table (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mac VARCHAR(20) NOT NULL,
    date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_mascot_info (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    "mLevel" SMALLINT NOT NULL,
    "mExp" INTEGER NOT NULL,
    "Flag" SMALLINT NOT NULL,
    "Tipo" SMALLINT NOT NULL,
    "RegDate" TIMESTAMPTZ NOT NULL,
    "Period" SMALLINT NOT NULL,
    "EndDate" TIMESTAMPTZ NULL,
    "Message" VARCHAR(30) NOT NULL,
    "IsCash" SMALLINT NOT NULL,
    "Price" INTEGER NOT NULL,
    "Valid" SMALLINT NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE pangya.pangya_msg_user (
    msg_idx BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    uid_from INTEGER NOT NULL,
    valid SMALLINT NOT NULL,
    msg VARCHAR(500) NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (msg_idx)
);

CREATE TABLE pangya.pangya_myroom (
    uid INTEGER NOT NULL,
    senha VARCHAR(15) NULL,
    public_lock SMALLINT NOT NULL,
    state SMALLINT NOT NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE pangya.pangya_new_box (
    id INTEGER NOT NULL,
    nome VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    opened_typeid INTEGER NOT NULL,
    numero INTEGER NOT NULL,
    tipo_open SMALLINT NOT NULL,
    tipo SMALLINT NOT NULL,
    message VARCHAR(80) NOT NULL,
    active SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_new_box_item (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    box_id INTEGER NOT NULL,
    nome VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    numero INTEGER NOT NULL,
    probabilidade INTEGER NULL,
    qntd INTEGER NOT NULL,
    raridade SMALLINT NOT NULL,
    duplicar SMALLINT NOT NULL,
    active SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_new_box_rare_win_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    box_typeid INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    raridade SMALLINT NOT NULL,
    win_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_new_card_pack (
    "index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    quantidade SMALLINT NOT NULL,
    tipo SMALLINT NOT NULL,
    "rate_N" SMALLINT NOT NULL,
    "rate_R" SMALLINT NOT NULL,
    "rate_SR" SMALLINT NOT NULL,
    "rate_SC" SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_new_cards (
    "index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    tipo SMALLINT NOT NULL,
    pack INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_new_course_drop (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rate_mana_artefact INTEGER NOT NULL,
    rate_grand_prix_ticket INTEGER NOT NULL,
    "rate_SSC_ticket" INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_new_course_drop_item (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course SMALLINT NOT NULL,
    tipo SMALLINT NOT NULL,
    typeid INTEGER NOT NULL,
    quantidade INTEGER NOT NULL,
    "probabilidade_3H" INTEGER NOT NULL,
    "probabilidade_6H" INTEGER NOT NULL,
    "probabilidade_9H" INTEGER NOT NULL,
    "probabilidade_18H" INTEGER NOT NULL,
    active SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_new_memorial_coin (
    tipo INTEGER NULL,
    nome VARCHAR(50) NULL,
    typeid INTEGER NULL,
    probabilidade INTEGER NULL
);

CREATE TABLE pangya.pangya_new_memorial_level (
    "level" INTEGER NOT NULL,
    gacha_start INTEGER NOT NULL,
    gacha_end INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_new_memorial_lucky_set (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    set_id INTEGER NOT NULL,
    nome VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_new_memorial_normal_item (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    tipo SMALLINT NOT NULL,
    active SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_new_memorial_rare_item (
    item_tipo INTEGER NULL,
    item_nome VARCHAR(50) NULL,
    item_typeid INTEGER NULL,
    item_probabilidade INTEGER NULL,
    item_gacha_number INTEGER NULL,
    item_active INTEGER NULL,
    coin_typeid INTEGER NULL
);

CREATE TABLE pangya.pangya_new_memorial_rare_win_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    coin_typeid INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL,
    item_raridade INTEGER NOT NULL,
    item_probabilidade INTEGER NOT NULL,
    win_date TIMESTAMPTZ NULL,
    memorial_nr INTEGER NULL
);

CREATE TABLE pangya.pangya_notice_list (
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message VARCHAR(1024) NULL,
    "replayCount" INTEGER NOT NULL,
    "refreshTime" INTEGER NOT NULL,
    PRIMARY KEY (notice_id)
);

CREATE TABLE pangya.pangya_papel_shop_config (
    "Numero" INTEGER NOT NULL,
    "Price_Normal" BIGINT NOT NULL,
    "Price_Big" BIGINT NOT NULL,
    "Limitted_YN" SMALLINT NOT NULL,
    "Update_Date" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_papel_shop_coupon (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    active SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_papel_shop_info (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    current_cnt SMALLINT NOT NULL,
    remain_cnt SMALLINT NOT NULL,
    limit_cnt SMALLINT NOT NULL,
    last_update TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_papel_shop_item (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Nome" VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    numero INTEGER NOT NULL,
    tipo SMALLINT NOT NULL,
    active SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_papel_shop_rare_win_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    ball_color SMALLINT NOT NULL,
    probabilidade INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_personal_shop_config (
    "Index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" VARCHAR(50) NOT NULL,
    "ID" INTEGER NOT NULL,
    "Price" INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NULL,
    PRIMARY KEY ("Index")
);

CREATE TABLE pangya.pangya_personal_shop_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_sell_uid INTEGER NOT NULL,
    player_buy_uid INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_id_sell INTEGER NOT NULL,
    item_id_buy INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL,
    item_pang BIGINT NOT NULL,
    total_pang BIGINT NOT NULL,
    reg_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_player_birth_day_log (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserID" INTEGER NULL,
    "LOGIN" VARCHAR(50) NULL,
    "SendDate" DATE NULL
);

CREATE TABLE pangya.pangya_player_ip (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    ip VARCHAR(18) NOT NULL,
    block_beta SMALLINT NOT NULL,
    flag_day SMALLINT NOT NULL,
    change_count INTEGER NOT NULL,
    change_date TIMESTAMPTZ NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_player_location (
    "UID" INTEGER NOT NULL,
    channel SMALLINT NOT NULL,
    lobby SMALLINT NOT NULL,
    room SMALLINT NOT NULL,
    place SMALLINT NOT NULL,
    "RoomId" UUID NULL
);

CREATE TABLE pangya.pangya_point_event (
    uid INTEGER NOT NULL,
    points BIGINT NOT NULL,
    limit_buy BIGINT NOT NULL,
    last_day TIMESTAMPTZ NULL,
    reg_date TIMESTAMPTZ NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE pangya.pangya_point_event_items (
    "NAME" VARCHAR(120) NOT NULL,
    "TYPEID" INTEGER NOT NULL,
    "ICON" VARCHAR(50) NULL,
    "PRICE" INTEGER NULL,
    "IFF_TYPE" SMALLINT NULL,
    "CHAR_TYPE" INTEGER NULL,
    "ACTIVED" INTEGER NULL
);

CREATE TABLE pangya.pangya_quest (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    achievement_id INTEGER NOT NULL,
    uid INTEGER NOT NULL,
    "name" VARCHAR(100) NULL,
    typeid INTEGER NOT NULL,
    counter_item_id INTEGER NOT NULL,
    "Date" TIMESTAMPTZ NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pangya.pangya_quest_clear (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    quest_id INTEGER NOT NULL,
    "option" SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_rank_antes (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "position" INTEGER NOT NULL,
    "UID" INTEGER NOT NULL,
    tipo_rank SMALLINT NOT NULL,
    tipo_rank_seq SMALLINT NOT NULL,
    valor INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_rank_atual (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "position" INTEGER NOT NULL,
    "UID" INTEGER NOT NULL,
    tipo_rank SMALLINT NOT NULL,
    tipo_rank_seq SMALLINT NOT NULL,
    valor INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_rank_atual_character (
    uid INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    itemid_parts_1 INTEGER NOT NULL,
    itemid_parts_2 INTEGER NOT NULL,
    itemid_parts_3 INTEGER NOT NULL,
    itemid_parts_4 INTEGER NOT NULL,
    itemid_parts_5 INTEGER NOT NULL,
    itemid_parts_6 INTEGER NOT NULL,
    itemid_parts_7 INTEGER NOT NULL,
    itemid_parts_8 INTEGER NOT NULL,
    itemid_parts_9 INTEGER NOT NULL,
    itemid_parts_10 INTEGER NOT NULL,
    itemid_parts_11 INTEGER NOT NULL,
    itemid_parts_12 INTEGER NOT NULL,
    itemid_parts_13 INTEGER NOT NULL,
    itemid_parts_14 INTEGER NOT NULL,
    itemid_parts_15 INTEGER NOT NULL,
    itemid_parts_16 INTEGER NOT NULL,
    itemid_parts_17 INTEGER NOT NULL,
    itemid_parts_18 INTEGER NOT NULL,
    itemid_parts_19 INTEGER NOT NULL,
    itemid_parts_20 INTEGER NOT NULL,
    itemid_parts_21 INTEGER NOT NULL,
    itemid_parts_22 INTEGER NOT NULL,
    itemid_parts_23 INTEGER NOT NULL,
    itemid_parts_24 INTEGER NOT NULL,
    parts_1 INTEGER NOT NULL,
    parts_2 INTEGER NOT NULL,
    parts_3 INTEGER NOT NULL,
    parts_4 INTEGER NOT NULL,
    parts_5 INTEGER NOT NULL,
    parts_6 INTEGER NOT NULL,
    parts_7 INTEGER NOT NULL,
    parts_8 INTEGER NOT NULL,
    parts_9 INTEGER NOT NULL,
    parts_10 INTEGER NOT NULL,
    parts_11 INTEGER NOT NULL,
    parts_12 INTEGER NOT NULL,
    parts_13 INTEGER NOT NULL,
    parts_14 INTEGER NOT NULL,
    parts_15 INTEGER NOT NULL,
    parts_16 INTEGER NOT NULL,
    parts_17 INTEGER NOT NULL,
    parts_18 INTEGER NOT NULL,
    parts_19 INTEGER NOT NULL,
    parts_20 INTEGER NOT NULL,
    parts_21 INTEGER NOT NULL,
    parts_22 INTEGER NOT NULL,
    parts_23 INTEGER NOT NULL,
    parts_24 INTEGER NOT NULL,
    default_hair SMALLINT NOT NULL,
    default_shirts SMALLINT NOT NULL,
    gift_flag SMALLINT NOT NULL,
    "PCL0" SMALLINT NOT NULL,
    "PCL1" SMALLINT NOT NULL,
    "PCL2" SMALLINT NOT NULL,
    "PCL3" SMALLINT NOT NULL,
    "PCL4" SMALLINT NOT NULL,
    purchase SMALLINT NOT NULL,
    "AUXPARTS_1" INTEGER NOT NULL,
    "AUXPARTS_2" INTEGER NOT NULL,
    "AUXPARTS_3" INTEGER NOT NULL,
    "AUXPARTS_4" INTEGER NOT NULL,
    "AUXPARTS_5" INTEGER NOT NULL,
    "CutIn_1" INTEGER NOT NULL,
    "CutIn_2" INTEGER NOT NULL,
    "CutIn_3" INTEGER NOT NULL,
    "CutIn_4" INTEGER NOT NULL,
    mastery INTEGER NOT NULL,
    "CARD_CHARACTER_1" INTEGER NOT NULL,
    "CARD_CHARACTER_2" INTEGER NOT NULL,
    "CARD_CHARACTER_3" INTEGER NOT NULL,
    "CARD_CHARACTER_4" INTEGER NOT NULL,
    "CARD_CADDIE_1" INTEGER NOT NULL,
    "CARD_CADDIE_2" INTEGER NOT NULL,
    "CARD_CADDIE_3" INTEGER NOT NULL,
    "CARD_CADDIE_4" INTEGER NOT NULL,
    "CARD_NPC_1" INTEGER NOT NULL,
    "CARD_NPC_2" INTEGER NOT NULL,
    "CARD_NPC_3" INTEGER NOT NULL,
    "CARD_NPC_4" INTEGER NOT NULL,
    PRIMARY KEY (uid)
);

CREATE TABLE pangya.pangya_rank_config (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "refresh_time_H" INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_record (
    "UID" INTEGER NOT NULL,
    tipo SMALLINT NOT NULL,
    course SMALLINT NOT NULL,
    best_score SMALLINT NOT NULL,
    best_pang BIGINT NOT NULL,
    character_typeid INTEGER NOT NULL,
    event_score SMALLINT NOT NULL,
    tacada INTEGER NOT NULL,
    putt INTEGER NOT NULL,
    hole INTEGER NOT NULL,
    fairway INTEGER NOT NULL,
    puttin INTEGER NOT NULL,
    total_score INTEGER NOT NULL,
    holein INTEGER NOT NULL,
    assist SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_rescue_pwd_log (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    tipo SMALLINT NOT NULL,
    key_uniq UUID NOT NULL,
    state SMALLINT NOT NULL,
    send_date TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_reward_ssc (
    valor INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    tipo INTEGER NOT NULL
);

CREATE TABLE pangya.pangya_room_log (
    "index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RoomId" UUID NULL,
    "Name" VARCHAR(50) NULL,
    "Master_UID" INTEGER NULL,
    "Number_Players" INTEGER NULL,
    "Max_Players" INTEGER NULL,
    "GM_EVENT" INTEGER NULL,
    "Tipo" INTEGER NULL,
    "TipoEx" INTEGER NULL,
    "Modo" INTEGER NULL,
    "NaturalMode" INTEGER NULL,
    "ShotMode" INTEGER NULL,
    "QntdHole" INTEGER NULL,
    "Course" INTEGER NULL,
    "Hole" INTEGER NULL,
    "UID" INTEGER NULL,
    "Character" INTEGER NULL,
    "Club" INTEGER NULL,
    "Mascot" INTEGER NULL,
    "Caddie" INTEGER NULL,
    "SpecialShot" INTEGER NULL,
    "Score" NUMERIC(18,0) NOT NULL,
    "Exp" INTEGER NULL,
    "Pang" BIGINT NULL,
    "BonusPang" BIGINT NULL,
    "TacadaNum" INTEGER NULL,
    "TotalTacadaNum" INTEGER NULL,
    "Hio_Hit" INTEGER NULL,
    "Alba_Hit" INTEGER NULL,
    "Eagle_Hit" INTEGER NULL,
    "Birdie_Hit" INTEGER NULL,
    "Par_Hit" INTEGER NULL,
    "Bogey_Hit" INTEGER NULL,
    "DoubleBogey_Hit" INTEGER NULL,
    "TripleBogey_Hit" INTEGER NULL,
    "GiveUp" INTEGER NULL,
    "TimeOut" INTEGER NULL,
    "EnterAfterStarted" INTEGER NULL,
    "AssistFlag" INTEGER NULL,
    "Trofeu" INTEGER NULL,
    "FinishGame" INTEGER NULL,
    "Data" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_roullete_event_item (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" VARCHAR(50) NOT NULL,
    "TypeID" INTEGER NOT NULL,
    "Probabilidade" INTEGER NOT NULL,
    "Numero" INTEGER NOT NULL,
    "Tipo" INTEGER NOT NULL,
    "Active" SMALLINT NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE pangya.pangya_roullete_event_rate (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" VARCHAR(100) NULL,
    tipo INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pangya.pangya_scratch_item (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" VARCHAR(50) NOT NULL,
    "TypeID" INTEGER NOT NULL,
    "Probabilidade" INTEGER NOT NULL,
    "Numero" INTEGER NOT NULL,
    "Tipo" INTEGER NOT NULL,
    "Active" SMALLINT NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE pangya.pangya_scratch_rate (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" VARCHAR(100) NULL,
    tipo INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pangya.pangya_server_list (
    "Name" VARCHAR(50) NOT NULL,
    "UID" INTEGER NOT NULL,
    "IP" VARCHAR(20) NOT NULL,
    "Port" INTEGER NOT NULL,
    "MaxUser" INTEGER NOT NULL,
    "CurrUser" INTEGER NOT NULL,
    "Type" SMALLINT NOT NULL,
    "UpdateTime" TIMESTAMPTZ NOT NULL,
    "State" SMALLINT NOT NULL,
    "PCBangUser" SMALLINT NOT NULL,
    "PangRate" INTEGER NOT NULL,
    "ServerVersion" VARCHAR(40) NOT NULL,
    "ClientVersion" VARCHAR(20) NOT NULL,
    property INTEGER NOT NULL,
    "AngelicWingsNum" INTEGER NOT NULL,
    "EventFlag" SMALLINT NOT NULL,
    "ExpRate" INTEGER NOT NULL,
    "RareItemRate" INTEGER NOT NULL,
    "CookieItemRate" INTEGER NOT NULL,
    "ServiceControl" INTEGER NOT NULL,
    "ImgNo" SMALLINT NOT NULL,
    "AppRate" SMALLINT NOT NULL,
    "ScratchRate" SMALLINT NOT NULL,
    "EventMap" INTEGER NOT NULL,
    "EventDropRate" INTEGER NOT NULL,
    "HanbitUser" INTEGER NOT NULL,
    "ParanUser" INTEGER NOT NULL,
    "AuthState" SMALLINT NOT NULL,
    "MasteryRate" SMALLINT NOT NULL,
    "TreasureRate" SMALLINT NOT NULL,
    "ChuvaRate" SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_shop_gift (
    gift_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gift_name VARCHAR(100) NOT NULL,
    item_name VARCHAR(50) NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL,
    item_qntd_time INTEGER NOT NULL,
    item_period INTEGER NOT NULL,
    required_price INTEGER NOT NULL,
    end_date TIMESTAMPTZ NULL,
    reg_date TIMESTAMPTZ NULL,
    PRIMARY KEY (gift_id)
);

CREATE TABLE pangya.pangya_shop_gift_log (
    "index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    gift_id INTEGER NOT NULL,
    item_typeid INTEGER NOT NULL,
    item_qntd INTEGER NOT NULL,
    reg_date TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_shutdown_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_shutdown TIMESTAMPTZ NULL,
    "replayCount" INTEGER NOT NULL,
    "refreshTime" INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pangya.pangya_ticker_list (
    ticker_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message VARCHAR(500) NOT NULL,
    nick VARCHAR(22) NOT NULL,
    "replayCount" INTEGER NOT NULL,
    "refreshTime" INTEGER NOT NULL,
    PRIMARY KEY (ticker_id)
);

CREATE TABLE pangya.pangya_ticket_report (
    idx BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trofel_typeid INTEGER NOT NULL,
    flag SMALLINT NOT NULL,
    reg_date TIMESTAMPTZ NULL,
    tipo INTEGER NOT NULL,
    PRIMARY KEY (idx)
);

CREATE TABLE pangya.pangya_ticket_report_dados (
    report_id BIGINT NOT NULL,
    player_uid INTEGER NOT NULL,
    player_score SMALLINT NOT NULL,
    player_medalha SMALLINT NOT NULL,
    player_trofel SMALLINT NOT NULL,
    player_pang BIGINT NOT NULL,
    player_bonus_pang BIGINT NOT NULL,
    player_exp INTEGER NOT NULL,
    player_mascot_typeid INTEGER NOT NULL,
    player_state SMALLINT NOT NULL,
    flag_item_pang SMALLINT NOT NULL,
    flag_premium_user SMALLINT NOT NULL,
    finish_date TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_tiki_points (
    "UID" INTEGER NOT NULL,
    "Tiki_Points" BIGINT NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL,
    "MOD_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.pangya_tiki_points_items (
    "INDEX" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ITEM_NAME" VARCHAR(50) NULL,
    "ITEM_TYPEID" INTEGER NOT NULL,
    "ITEM_QNTD" INTEGER NOT NULL,
    "REQ_POINTS" INTEGER NULL,
    "ITEM_FLAG" INTEGER NULL,
    "ITEM_ACTIVE" INTEGER NULL,
    "REG_DATE" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_treasure_hunter_event_item (
    "Index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Position" INTEGER NOT NULL,
    "Name" VARCHAR(50) NULL,
    typeid INTEGER NOT NULL,
    quantidade INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    tipo INTEGER NOT NULL,
    flag SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_treasure_item (
    "Name" VARCHAR(50) NULL,
    typeid INTEGER NOT NULL,
    quantidade INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL,
    tipo INTEGER NOT NULL,
    flag SMALLINT NOT NULL
);

CREATE TABLE pangya.pangya_trofel_especial (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE pangya.pangya_trofel_grandprix (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    qntd INTEGER NOT NULL,
    PRIMARY KEY (item_id)
);

CREATE TABLE pangya.pangya_user_equip (
    "UID" INTEGER NOT NULL,
    caddie_id INTEGER NOT NULL,
    character_id INTEGER NOT NULL,
    club_id INTEGER NOT NULL,
    ball_type INTEGER NOT NULL,
    item_slot_1 INTEGER NOT NULL,
    item_slot_2 INTEGER NOT NULL,
    item_slot_3 INTEGER NOT NULL,
    item_slot_4 INTEGER NOT NULL,
    item_slot_5 INTEGER NOT NULL,
    item_slot_6 INTEGER NOT NULL,
    item_slot_7 INTEGER NOT NULL,
    item_slot_8 INTEGER NOT NULL,
    item_slot_9 INTEGER NOT NULL,
    item_slot_10 INTEGER NOT NULL,
    "Skin_1" INTEGER NOT NULL,
    "Skin_2" INTEGER NOT NULL,
    "Skin_3" INTEGER NOT NULL,
    "Skin_4" INTEGER NOT NULL,
    "Skin_5" INTEGER NOT NULL,
    "Skin_6" INTEGER NOT NULL,
    mascot_id INTEGER NOT NULL,
    poster_1 INTEGER NOT NULL,
    poster_2 INTEGER NOT NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.pangya_user_macro (
    "UID" INTEGER NOT NULL,
    "Macro1" VARCHAR(500) NULL,
    "Macro2" VARCHAR(500) NULL,
    "Macro3" VARCHAR(500) NULL,
    "Macro4" VARCHAR(500) NULL,
    "Macro5" VARCHAR(500) NULL,
    "Macro6" VARCHAR(500) NULL,
    "Macro7" VARCHAR(500) NULL,
    "Macro8" VARCHAR(500) NULL,
    "Macro9" VARCHAR(500) NULL,
    "Macro10" VARCHAR(500) NULL
);

CREATE TABLE pangya.pangya_weblink_cookies_key (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    "key" VARCHAR(8) NOT NULL,
    valid SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_weblink_key (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid INTEGER NOT NULL,
    "key" VARCHAR(8) NOT NULL,
    valid SMALLINT NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.pangya_world_tour_config (
    "EventID" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" VARCHAR(100) NOT NULL,
    "StartDate" TIMESTAMPTZ NOT NULL,
    "EndDate" TIMESTAMPTZ NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("EventID")
);

CREATE TABLE pangya.pangya_world_tour_event (
    "Index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "Course" INTEGER NOT NULL,
    "Completed" INTEGER NOT NULL,
    "Finish_Data" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_world_tour_event_items (
    "INDEX" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TOUR_EVENT" VARCHAR(50) NULL,
    "ITEM_NAME" VARCHAR(50) NULL,
    "ITEM_TYPEID" INTEGER NOT NULL,
    "ITEM_QNTD" INTEGER NOT NULL,
    "ITEM_QNTD_TIME" INTEGER NOT NULL,
    "EVENT_DESCRIPTION" VARCHAR(255) NULL,
    "END_EVENT" TIMESTAMPTZ NULL,
    "REG_DATE" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.pangya_world_tour_event_log (
    "Index" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "SendGift" INTEGER NOT NULL,
    "Finish_Data" TIMESTAMPTZ NULL
);

CREATE TABLE pangya.quest_items (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    stuff_typeid INTEGER NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.quest_stuffs (
    "index" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    typeid INTEGER NOT NULL,
    nome VARCHAR(100) NOT NULL,
    counter_typeid INTEGER NOT NULL,
    counter_qntd INTEGER NOT NULL,
    PRIMARY KEY ("index")
);

CREATE TABLE pangya.scratchy_item (
    "Name" VARCHAR(50) NOT NULL,
    "TypeID" INTEGER NOT NULL,
    "Numero" INTEGER NOT NULL,
    "Quantidade" INTEGER NOT NULL,
    "Probabilidade" INTEGER NOT NULL,
    "Tipo" INTEGER NOT NULL,
    flag SMALLINT NOT NULL,
    "Active" SMALLINT NOT NULL
);

CREATE TABLE pangya.scratchy_rare_win (
    "UID" INTEGER NOT NULL,
    "TypeID" INTEGER NOT NULL,
    "REG_DATE" TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.scratchy_rate (
    nome VARCHAR(50) NULL,
    tipo INTEGER NOT NULL,
    probabilidade INTEGER NOT NULL
);

CREATE TABLE pangya.td_char_equip_s4 (
    "SEQ" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "CHAR_ITEMID" INTEGER NOT NULL,
    "ITEMID" INTEGER NOT NULL,
    "IN_DATE" TIMESTAMPTZ NULL,
    "EQUIP_NUM" INTEGER NOT NULL,
    "EQUIP_TYPE" INTEGER NOT NULL,
    "USE_YN" VARCHAR(1) NULL,
    PRIMARY KEY ("SEQ")
);

CREATE TABLE pangya.td_room_data (
    "MYROOM_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UID" INTEGER NOT NULL,
    "ROOM_NO" INTEGER NOT NULL,
    "TYPEID" INTEGER NOT NULL,
    "POS_X" REAL NOT NULL,
    "POS_Y" REAL NOT NULL,
    "POS_Z" REAL NOT NULL,
    "POS_R" REAL NOT NULL,
    "MOD_SEQ" INTEGER NOT NULL,
    "DISPLAY_YN" VARCHAR(1) NOT NULL,
    "USE_YN" VARCHAR(1) NOT NULL,
    "MOD_DT" TIMESTAMPTZ NULL,
    valid SMALLINT NULL,
    PRIMARY KEY ("MYROOM_ID")
);

CREATE TABLE pangya.trofel_stat (
    "UID" BIGINT NOT NULL,
    "AMA_6_G" SMALLINT NOT NULL,
    "AMA_6_S" SMALLINT NOT NULL,
    "AMA_6_B" SMALLINT NOT NULL,
    "AMA_5_G" SMALLINT NOT NULL,
    "AMA_5_S" SMALLINT NOT NULL,
    "AMA_5_B" SMALLINT NOT NULL,
    "AMA_4_G" SMALLINT NOT NULL,
    "AMA_4_S" SMALLINT NOT NULL,
    "AMA_4_B" SMALLINT NOT NULL,
    "AMA_3_G" SMALLINT NOT NULL,
    "AMA_3_S" SMALLINT NOT NULL,
    "AMA_3_B" SMALLINT NOT NULL,
    "AMA_2_G" SMALLINT NOT NULL,
    "AMA_2_S" SMALLINT NOT NULL,
    "AMA_2_B" SMALLINT NOT NULL,
    "AMA_1_G" SMALLINT NOT NULL,
    "AMA_1_S" SMALLINT NOT NULL,
    "AMA_1_B" SMALLINT NOT NULL,
    "PRO_1_G" SMALLINT NOT NULL,
    "PRO_1_S" SMALLINT NOT NULL,
    "PRO_1_B" SMALLINT NOT NULL,
    "PRO_2_G" SMALLINT NOT NULL,
    "PRO_2_S" SMALLINT NOT NULL,
    "PRO_2_B" SMALLINT NOT NULL,
    "PRO_3_G" SMALLINT NOT NULL,
    "PRO_3_S" SMALLINT NOT NULL,
    "PRO_3_B" SMALLINT NOT NULL,
    "PRO_4_G" SMALLINT NOT NULL,
    "PRO_4_S" SMALLINT NOT NULL,
    "PRO_4_B" SMALLINT NOT NULL,
    "PRO_5_G" SMALLINT NOT NULL,
    "PRO_5_S" SMALLINT NOT NULL,
    "PRO_5_B" SMALLINT NOT NULL,
    "PRO_6_G" SMALLINT NOT NULL,
    "PRO_6_S" SMALLINT NOT NULL,
    "PRO_6_B" SMALLINT NOT NULL,
    "PRO_7_G" SMALLINT NOT NULL,
    "PRO_7_S" SMALLINT NOT NULL,
    "PRO_7_B" SMALLINT NOT NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.tu_ucc (
    "UID" BIGINT NOT NULL,
    "TYPEID" BIGINT NOT NULL,
    "UCCIDX" VARCHAR(8) NULL,
    "SEQ" INTEGER NOT NULL,
    "UCC_NAME" VARCHAR(50) NULL,
    "USE_YN" VARCHAR(1) NOT NULL,
    "IN_DATE" TIMESTAMPTZ NOT NULL,
    "COPIER" INTEGER NULL,
    "ITEM_ID" NUMERIC(20,0) NOT NULL,
    "COPIER_NICK" VARCHAR(32) NULL,
    "DRAW_DT" TIMESTAMPTZ NULL,
    "STATUS" SMALLINT NOT NULL,
    "Flag" SMALLINT NOT NULL,
    "SKEY" VARCHAR(20) NULL,
    "TRADE" SMALLINT NOT NULL,
    PRIMARY KEY ("UID", "TYPEID", "SEQ", "ITEM_ID")
);

CREATE TABLE pangya.tutorial (
    "UID" BIGINT NOT NULL,
    "Rookie" INTEGER NOT NULL,
    "Beginner" INTEGER NOT NULL,
    "Advancer" INTEGER NOT NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.user_info (
    "UID" BIGINT NOT NULL,
    "Tacadas" BIGINT NOT NULL,
    "Putt" BIGINT NOT NULL,
    "Tempo" BIGINT NOT NULL,
    "Tempo tacadas" BIGINT NOT NULL,
    "Max_distancia" REAL NOT NULL,
    "Acerto_pangya" BIGINT NOT NULL,
    "Bunker" INTEGER NOT NULL,
    "O.B" BIGINT NOT NULL,
    "Total_distancia" BIGINT NOT NULL,
    "Holes" BIGINT NOT NULL,
    "Holein" INTEGER NOT NULL,
    "HIO" BIGINT NOT NULL,
    "Timeout" SMALLINT NOT NULL,
    "Fairway" BIGINT NOT NULL,
    "Albatross" BIGINT NOT NULL,
    "MaConduta" INTEGER NOT NULL,
    "Acerto_Putt" BIGINT NOT NULL,
    "Long-putt" REAL NOT NULL,
    "Chip-in" REAL NOT NULL,
    "Xp" BIGINT NOT NULL,
    "level" SMALLINT NOT NULL,
    "Pang" BIGINT NOT NULL,
    "Media_score" INTEGER NOT NULL,
    "BestScore0" SMALLINT NOT NULL,
    "BestScore1" SMALLINT NOT NULL,
    "BestScore2" SMALLINT NOT NULL,
    "BestScore3" SMALLINT NOT NULL,
    "BestScore4" SMALLINT NOT NULL,
    "MaxPang0" BIGINT NOT NULL,
    "maxPang1" BIGINT NOT NULL,
    "maxPang2" BIGINT NOT NULL,
    "maxPang3" BIGINT NOT NULL,
    "maxPang4" BIGINT NOT NULL,
    "SumPang" BIGINT NOT NULL,
    "EventFlag" SMALLINT NOT NULL,
    "Jogado" BIGINT NOT NULL,
    "Quitado" BIGINT NOT NULL,
    "SkinPang" BIGINT NOT NULL,
    "SkinWin" INTEGER NOT NULL,
    "SkinLose" INTEGER NOT NULL,
    "SkinRunHole" INTEGER NOT NULL,
    "SkinStrikePoint" INTEGER NOT NULL,
    "SkinAllinCount" INTEGER NOT NULL,
    "Todos_combos" BIGINT NOT NULL,
    "Combos" BIGINT NOT NULL,
    "TeamWin" INTEGER NOT NULL,
    "TeamGames" INTEGER NOT NULL,
    "Teamhole" BIGINT NOT NULL,
    "LadderPoint" INTEGER NOT NULL,
    "LadderWin" INTEGER NOT NULL,
    "LadderLose" INTEGER NOT NULL,
    "LadderDraw" INTEGER NOT NULL,
    "LadderHole" INTEGER NOT NULL,
    "EventValue" SMALLINT NOT NULL,
    "NaoSei" INTEGER NOT NULL,
    "MaxJogoNaoSei" INTEGER NOT NULL,
    "JogosNaoSei" INTEGER NOT NULL,
    "GameCountSeason" INTEGER NOT NULL,
    "Cookie" BIGINT NOT NULL,
    total_pang_win_game BIGINT NOT NULL,
    lucky_medal INTEGER NOT NULL,
    fast_medal INTEGER NOT NULL,
    best_drive_medal INTEGER NOT NULL,
    best_chipin_medal INTEGER NOT NULL,
    best_puttin_medal INTEGER NOT NULL,
    best_recovery_medal INTEGER NOT NULL,
    "16bit_naosei" SMALLINT NOT NULL,
    PRIMARY KEY ("UID")
);

CREATE TABLE pangya.web_audit_log (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_uid INTEGER NOT NULL,
    action VARCHAR(80) NOT NULL,
    item_id INTEGER NULL,
    ip_address VARCHAR(45) NOT NULL,
    details TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE pangya.web_marketplace_listing (
    listing_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seller_uid INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    price BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL,
    status VARCHAR(10) NOT NULL,
    buyer_uid INTEGER NULL,
    created_at TIMESTAMPTZ NOT NULL,
    sold_at TIMESTAMPTZ NULL
);

CREATE TABLE pangya.web_shop_transaction (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    buyer_uid INTEGER NOT NULL,
    seller_uid INTEGER NULL,
    item_id INTEGER NULL,
    typeid INTEGER NULL,
    amount BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL,
    kind VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

-- indexes
CREATE UNIQUE INDEX "IX_pangya_change_nickname_log_1" ON pangya.pangya_change_nickname_log ("index");
CREATE UNIQUE INDEX "IX_pangya_change_pwd_log_1" ON pangya.pangya_change_pwd_log (uid);
CREATE UNIQUE INDEX "IX_pangya_donation_item_log_1" ON pangya.pangya_donation_item_log ("index");
CREATE UNIQUE INDEX "IX_pangya_donation_log_1" ON pangya.pangya_donation_log ("index");
CREATE INDEX "IDX_EVENTO_ID" ON pangya.pangya_event_itens_site ("EVENTO_ID");
CREATE UNIQUE INDEX "IX_pangya_gm_gift_web_log_1" ON pangya.pangya_gm_gift_web_log ("index");
CREATE UNIQUE INDEX "IX_pangya_guild_bbs_1" ON pangya.pangya_guild_bbs ("SEQ");
CREATE INDEX "IX_pangya_guild_bbs_2" ON pangya.pangya_guild_bbs ("OWNER_UID");
CREATE UNIQUE INDEX "IX_pangya_guild_bbs_res_1" ON pangya.pangya_guild_bbs_res ("SEQ");
CREATE INDEX "IX_pangya_guild_bbs_res_2" ON pangya.pangya_guild_bbs_res ("BBS_SEQ");
CREATE INDEX "IX_pangya_guild_bbs_res_3" ON pangya.pangya_guild_bbs_res ("OWNER_UID");
CREATE UNIQUE INDEX "IX_pangya_guild_intro_img_log_1" ON pangya.pangya_guild_intro_img_log ("index");
CREATE UNIQUE INDEX "IX_pangya.pangya_guild_mark_log_1" ON pangya.pangya_guild_mark_log ("index");
CREATE UNIQUE INDEX "IX_pangya_guild_match_1" ON pangya.pangya_guild_match ("index");
CREATE INDEX "IX_pangya_guild_match_2" ON pangya.pangya_guild_match (guild_1_uid);
CREATE INDEX "IX_pangya_guild_match_3" ON pangya.pangya_guild_match (guild_2_uid);
CREATE UNIQUE INDEX "IX_pangya_guild_notice_1" ON pangya.pangya_guild_notice ("SEQ");
CREATE INDEX "IX_pangya_guild_notice_2" ON pangya.pangya_guild_notice ("GUILD_UID");
CREATE INDEX "IX_pangya_guild_notice_3" ON pangya.pangya_guild_notice ("OWNER_UID");
CREATE UNIQUE INDEX "IX_pangya_guild_private_bbs_1" ON pangya.pangya_guild_private_bbs ("SEQ");
CREATE INDEX "IX_pangya_guild_private_bbs_2" ON pangya.pangya_guild_private_bbs ("GUILD_UID");
CREATE INDEX "IX_pangya_guild_private_bbs_3" ON pangya.pangya_guild_private_bbs ("OWNER_UID");
CREATE UNIQUE INDEX "IX_pangya_guild_private_bbs_res_1" ON pangya.pangya_guild_private_bbs_res ("SEQ");
CREATE INDEX "IX_pangya_guild_private_bbs_res_2" ON pangya.pangya_guild_private_bbs_res ("GUILD_BBS_SEQ");
CREATE INDEX "IX_pangya_guild_private_bbs_res_3" ON pangya.pangya_guild_private_bbs_res ("OWNER_UID");
CREATE INDEX "IX_pangya_guild_update_activity" ON pangya.pangya_guild_update_activity ("OWNER_UPDATE");
CREATE UNIQUE INDEX "IX_pangya_mac_table_1" ON pangya.pangya_mac_table ("index");
CREATE UNIQUE INDEX "IX_pangya_personal_shop_log_1" ON pangya.pangya_personal_shop_log ("index");
CREATE INDEX "IX_pangya_rescue_pwd_log" ON pangya.pangya_rescue_pwd_log (uid);
CREATE UNIQUE INDEX "IX_pangya_rescue_pwd_log_3" ON pangya.pangya_rescue_pwd_log ("index");
CREATE INDEX "IX_web_audit_log_actor_created" ON pangya.web_audit_log (actor_uid, created_at);
CREATE INDEX "IX_web_marketplace_listing_active" ON pangya.web_marketplace_listing (status, created_at);
CREATE UNIQUE INDEX "UX_web_marketplace_listing_active_item" ON pangya.web_marketplace_listing (item_id);
CREATE INDEX "IX_web_shop_transaction_buyer_created" ON pangya.web_shop_transaction (buyer_uid, created_at);
CREATE UNIQUE INDEX "IX_account" ON pangya.account ("ID");
CREATE UNIQUE INDEX "IX_pangya_1st_aniversary_player_win_cp" ON pangya.pangya_1st_anniversary_player_win_cp ("UID");
CREATE UNIQUE INDEX "IX_pangya_achievement" ON pangya.pangya_achievement ("ID_ACHIEVEMENT");
CREATE UNIQUE INDEX "IX_pangya.auth_key" ON pangya.pangya_auth_key ("index");
CREATE UNIQUE INDEX "IX_pangya_card_equip" ON pangya.pangya_card_equip ("index");
CREATE UNIQUE INDEX "IX_pangya_change_email_log" ON pangya.pangya_change_email_log ("index");
CREATE UNIQUE INDEX "IX_pangya_change_nickname_log" ON pangya.pangya_change_nickname_log ("index");
CREATE UNIQUE INDEX "IX_pangya_change_pwd_log" ON pangya.pangya_change_pwd_log (uid);
CREATE UNIQUE INDEX "IX_pangya_comet_refill" ON pangya.pangya_comet_refill ("index");
CREATE UNIQUE INDEX "IX_pangya_command_gm_log" ON pangya.pangya_command_gm_log ("index");
CREATE UNIQUE INDEX "IX_pangya_config" ON pangya.pangya_config ("UID");
CREATE UNIQUE INDEX "IX_pangya_cookie_point_item_log" ON pangya.pangya_cookie_point_item_log ("index");
CREATE UNIQUE INDEX "IX_pangya_cookie_point_log" ON pangya.pangya_cookie_point_log (id);
CREATE UNIQUE INDEX "IX_pangya.counter_item" ON pangya.pangya_counter_item ("Count_ID");
CREATE UNIQUE INDEX "IX_pangya_donation_epin" ON pangya.pangya_donation_epin (epin);
CREATE UNIQUE INDEX "IX_pangya_donation_epin_1" ON pangya.pangya_donation_epin (donation_id);
CREATE UNIQUE INDEX "IX_pangya_donation_item_log" ON pangya.pangya_donation_item_log ("index");
CREATE UNIQUE INDEX "IX_pangya_donation_log" ON pangya.pangya_donation_log ("index");
CREATE UNIQUE INDEX "IX_pangya_donation_new" ON pangya.pangya_donation_new (code);
CREATE UNIQUE INDEX "IX_pangya_gm_gift_web_log" ON pangya.pangya_gm_gift_web_log ("index");
CREATE UNIQUE INDEX "IX_pangya_guild" ON pangya.pangya_guild ("GUILD_UID");
CREATE UNIQUE INDEX "IX_pangya_guild_atividade_player" ON pangya.pangya_guild_atividade_player ("IDX");
CREATE UNIQUE INDEX "IX_pangya_guild_bbs" ON pangya.pangya_guild_bbs ("SEQ");
CREATE UNIQUE INDEX "IX_pangya_guild_bbs_res" ON pangya.pangya_guild_bbs_res ("SEQ");
CREATE UNIQUE INDEX "IX_pangya_guild_intro_img_log" ON pangya.pangya_guild_intro_img_log ("index");
CREATE UNIQUE INDEX "IX_pangya.pangya_guild_mark_log" ON pangya.pangya_guild_mark_log ("index");
CREATE UNIQUE INDEX "IX_pangya_guild_match" ON pangya.pangya_guild_match ("index");
CREATE UNIQUE INDEX "IX_pangya_guild_notice" ON pangya.pangya_guild_notice ("SEQ");
CREATE UNIQUE INDEX "IX_pangya_guild_private_bbs" ON pangya.pangya_guild_private_bbs ("SEQ");
CREATE UNIQUE INDEX "IX_pangya_guild_private_bbs_res" ON pangya.pangya_guild_private_bbs_res ("SEQ");
CREATE UNIQUE INDEX "IX_pangya_item_buff" ON pangya.pangya_item_buff ("index");
CREATE UNIQUE INDEX "IX_pangya_item_buy_shop_log" ON pangya.pangya_item_buy_shop_log ("index");
CREATE UNIQUE INDEX "IX_pangya_mac_table" ON pangya.pangya_mac_table ("index");
CREATE UNIQUE INDEX "IX_pangya_new_box" ON pangya.pangya_new_box (id);
CREATE UNIQUE INDEX "IX_pangya_new_box_rare_win_log" ON pangya.pangya_new_box_rare_win_log ("index");
CREATE UNIQUE INDEX "IX_pangya_new_course_drop_1" ON pangya.pangya_new_course_drop ("index");
CREATE UNIQUE INDEX "IX_pangya_new_course_drop" ON pangya.pangya_new_course_drop_item ("index");
CREATE UNIQUE INDEX "IX_pangya_new_memorial_level" ON pangya.pangya_new_memorial_level ("level");
CREATE UNIQUE INDEX "IX_pangya_new_memorial_lucky_set" ON pangya.pangya_new_memorial_lucky_set ("index");
CREATE UNIQUE INDEX "IX_pangya_new_memorial_normal_item" ON pangya.pangya_new_memorial_normal_item ("index");
CREATE UNIQUE INDEX "IX_pangya_new_memorial_rare_win_log" ON pangya.pangya_new_memorial_rare_win_log ("index");
CREATE UNIQUE INDEX "IX_pangya_papel_shop_coupon" ON pangya.pangya_papel_shop_coupon ("index");
CREATE UNIQUE INDEX "IX_pangya_papel_shop_info" ON pangya.pangya_papel_shop_info ("index");
CREATE UNIQUE INDEX "IX_pangya_papel_shop_item" ON pangya.pangya_papel_shop_item ("index");
CREATE UNIQUE INDEX "IX_pangya_papel_shop_rare_win" ON pangya.pangya_papel_shop_rare_win_log ("index");
CREATE UNIQUE INDEX "IX_pangya_personal_shop_log" ON pangya.pangya_personal_shop_log ("index");
CREATE UNIQUE INDEX "IX_pangya_player_location" ON pangya.pangya_player_location ("UID");
CREATE UNIQUE INDEX "UQ__pangya_q__3213E83E970124D3" ON pangya.pangya_quest (id);
CREATE UNIQUE INDEX "IX_pangya_rescue_pwd_log_2" ON pangya.pangya_rescue_pwd_log ("index");
CREATE UNIQUE INDEX "IX_pangya_server_list" ON pangya.pangya_server_list ("UID");
