#!/usr/bin/env python3
"""Translate MSSQL CREATE TABLE / INDEX from the Pangya dump into PostgreSQL.

Source of truth: SQL/bk-schema-mssql-complet2022.sql (C# reference).
Stored procedures are intentionally NOT converted: Java uses explicit SQL via Jdbi.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

PG_RESERVED = {
    "all", "analyse", "analyze", "and", "any", "array", "as", "asc", "asymmetric",
    "authorization", "binary", "both", "case", "cast", "check", "collate", "column",
    "concurrently", "constraint", "create", "cross", "current_catalog", "current_date",
    "current_role", "current_schema", "current_time", "current_timestamp", "current_user",
    "default", "deferrable", "desc", "distinct", "do", "else", "end", "except", "false",
    "fetch", "for", "foreign", "freeze", "from", "full", "grant", "group", "having",
    "ilike", "in", "initially", "inner", "intersect", "into", "is", "isnull", "join",
    "lateral", "leading", "left", "like", "limit", "localtime", "localtimestamp",
    "natural", "not", "notnull", "null", "offset", "on", "only", "or", "order", "outer",
    "overlaps", "placing", "primary", "references", "returning", "right", "select",
    "session_user", "similar", "some", "symmetric", "table", "tablesample", "then",
    "to", "trailing", "true", "union", "unique", "user", "using", "variadic", "verbose",
    "when", "where", "window", "with", "index", "option", "type", "name", "port",
    "key", "value", "level", "position", "comment", "owner", "timestamp", "time",
}


def quote_ident(name: str) -> str:
    name = name.strip().strip("[]")
    if not name:
        return name
    if (
        re.search(r"[^a-zA-Z0-9_]", name)
        or name.lower() in PG_RESERVED
        or name != name.lower()
        or name[0].isdigit()
    ):
        return '"' + name.replace('"', '""') + '"'
    return name


def map_type(mssql: str) -> str:
    t = re.sub(r"\s+", " ", mssql.strip().lower())
    identity = "identity" in t
    t = re.sub(r"\s+identity\s*\(\s*\d+\s*,\s*\d+\s*\)", "", t).strip()
    t = t.replace("[", "").replace("]", "")
    t = re.sub(r"\s+", " ", t).strip()

    mapping = None
    m = re.match(r"(nvarchar|varchar|nchar|char)\s*\(\s*(max|\d+)\s*\)", t)
    if m:
        kind, n = m.group(1), m.group(2)
        if n == "max":
            mapping = "TEXT"
        elif kind in ("nvarchar", "varchar"):
            mapping = f"VARCHAR({n})"
        else:
            mapping = f"CHAR({n})"
    elif t in ("ntext", "text", "xml", "varchar", "nvarchar"):
        mapping = "TEXT"
    elif t.startswith("datetime2") or t in ("datetime", "smalldatetime"):
        mapping = "TIMESTAMPTZ"
    elif t == "date":
        mapping = "DATE"
    elif t.startswith("time"):
        mapping = "TIME"
    elif t == "bit":
        mapping = "BOOLEAN"
    elif t == "tinyint":
        mapping = "SMALLINT"
    elif t == "smallint":
        mapping = "SMALLINT"
    elif t == "int":
        mapping = "INTEGER"
    elif t == "bigint":
        mapping = "BIGINT"
    elif t == "real":
        mapping = "REAL"
    elif t == "float":
        mapping = "DOUBLE PRECISION"
    elif t == "money":
        mapping = "NUMERIC(19,4)"
    elif t == "uniqueidentifier":
        mapping = "UUID"
    elif t in ("image", "varbinary(max)", "binary(max)"):
        mapping = "BYTEA"
    elif t.startswith("varbinary") or t.startswith("binary"):
        mapping = "BYTEA"
    else:
        nm = re.match(r"(numeric|decimal)(?:\s*\(\s*(\d+)(?:\s*,\s*(\d+))?\s*\))?$", t)
        if nm:
            p, s = nm.group(2), nm.group(3)
            if p and s:
                mapping = f"NUMERIC({p},{s})"
            elif p:
                mapping = f"NUMERIC({p})"
            else:
                mapping = "NUMERIC"
        else:
            raise ValueError(f"unmapped MSSQL type: {mssql!r}")

    if identity:
        if mapping.startswith("NUMERIC"):
            mapping = "BIGINT"
        mapping += " GENERATED BY DEFAULT AS IDENTITY"
    return mapping


COL_RE = re.compile(
    r"^\[(?P<name>[^\]]+)\]\s+\[(?P<type>[^\]]+)\](?P<rest>.*)$",
    re.DOTALL,
)


def parse_column(line: str) -> str | None:
    line = line.strip().rstrip(",")
    if line.upper().startswith("CONSTRAINT"):
        return None
    m = COL_RE.match(line)
    if not m:
        raise ValueError(f"cannot parse column: {line!r}")
    name = m.group("name")
    type_name = m.group("type")
    rest = m.group("rest")
    identity = bool(re.search(r"IDENTITY\s*\(", rest, re.I))
    not_null = bool(re.search(r"\bNOT NULL\b", rest, re.I))
    null = bool(re.search(r"\bNULL\b", rest, re.I)) and not not_null
    type_spec = f"[{type_name}]"
    len_m = re.match(r"\s*\(\s*(max|\d+)\s*\)", rest, re.I)
    num_m = re.match(r"\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)", rest, re.I)
    if num_m:
        type_spec += f"({num_m.group(1)},{num_m.group(2)})"
    elif len_m:
        type_spec += f"({len_m.group(1)})"
    if identity:
        idm = re.search(r"IDENTITY\s*\(\s*\d+\s*,\s*\d+\s*\)", rest, re.I)
        type_spec += " " + (idm.group(0) if idm else "IDENTITY(1,1)")
    pg_type = map_type(type_spec)
    null_sql = " NOT NULL" if not_null else (" NULL" if null else "")
    return f"    {quote_ident(name)} {pg_type}{null_sql}"


def extract_pk(block: str) -> list[str]:
    m = re.search(
        r"CONSTRAINT\s+\[([^\]]+)\]\s+PRIMARY KEY(?:\s+CLUSTERED)?\s*\((.*?)\)",
        block,
        re.S | re.I,
    )
    if not m:
        return []
    cols = re.findall(r"\[([^\]]+)\]", m.group(2))
    return cols


INDEX_RE = re.compile(
    r"CREATE\s+(UNIQUE\s+)?(?:NONCLUSTERED\s+|CLUSTERED\s+)?INDEX\s+\[([^\]]+)\]\s+ON\s+\[pangya\]\.\[([^\]]+)\]\s*\((.*?)\)",
    re.S | re.I,
)

ALTER_UNIQUE_RE = re.compile(
    r"ALTER TABLE \[pangya\]\.\[([^\]]+)\] ADD\s+CONSTRAINT\s+\[([^\]]+)\]\s+UNIQUE(?:\s+NONCLUSTERED)?\s*\((.*?)\)",
    re.S | re.I,
)


def convert_indexes(sql: str) -> list[str]:
    out = []
    seen = set()
    for m in INDEX_RE.finditer(sql):
        unique, name, table, cols_block = m.groups()
        if "temp_" in table.lower():
            continue
        cols = re.findall(r"\[([^\]]+)\]", cols_block)
        key = (name.lower(), table.lower(), tuple(c.lower() for c in cols))
        if key in seen:
            continue
        seen.add(key)
        u = "UNIQUE " if unique else ""
        out.append(
            f"CREATE {u}INDEX {quote_ident(name)} ON pangya.{quote_ident(table)} ("
            + ", ".join(quote_ident(c) for c in cols)
            + ");"
        )
    for m in ALTER_UNIQUE_RE.finditer(sql):
        table, name, cols_block = m.groups()
        cols = re.findall(r"\[([^\]]+)\]", cols_block)
        key = (name.lower(), table.lower(), tuple(c.lower() for c in cols))
        if key in seen:
            continue
        seen.add(key)
        out.append(
            f"CREATE UNIQUE INDEX {quote_ident(name)} ON pangya.{quote_ident(table)} ("
            + ", ".join(quote_ident(c) for c in cols)
            + ");"
        )
    return out


HEADER = """-- V1 Pangya schema translated from SQL/bk-schema-mssql-complet2022.sql (C# reference).
-- Type mapping: NVARCHAR/VARCHAR(max)->TEXT, DATETIME/DATETIME2->TIMESTAMPTZ,
-- IDENTITY->GENERATED BY DEFAULT AS IDENTITY, TINYINT->SMALLINT, BIT->BOOLEAN,
-- UNIQUEIDENTIFIER->UUID, IMAGE/VARBINARY->BYTEA.
-- Stored procedures (502) are NOT ported: servers will use explicit Jdbi SQL.
-- Original column names are preserved (quoted) including spaces and punctuation.

CREATE SCHEMA IF NOT EXISTS pangya;

"""


def read_sql(path: Path) -> str:
    raw = path.read_bytes()
    if raw.startswith(b"\xff\xfe") or raw.startswith(b"\xfe\xff"):
        return raw.decode("utf-16")
    if raw.startswith(b"\xef\xbb\xbf"):
        return raw.decode("utf-8-sig")
    return raw.decode("utf-8")


def convert_tables(sql: str) -> tuple[list[str], int]:
    out = []
    count = 0
    # Table closer is a line that is exactly ") ON [PRIMARY]" (optional TEXTIMAGE).
    closer = re.compile(r"\n\) ON \[PRIMARY\](?: TEXTIMAGE_ON \[PRIMARY\])?\s*(?:\r)?\n", re.I)
    starts = list(re.finditer(r"CREATE TABLE \[pangya\]\.\[([^\]]+)\]\s*\(", sql, re.I))
    for i, m in enumerate(starts):
        table = m.group(1)
        if table.lower().startswith("temp_"):
            continue
        rest = sql[m.end() :]
        cm = closer.search("\n" + rest)
        if not cm:
            raise ValueError(f"no closer for table {table}")
        body = rest[: cm.start()]
        pk = extract_pk(body)
        col_lines = []
        for raw in body.splitlines():
            raw = raw.strip().rstrip(",")
            if not raw or raw.upper().startswith("CONSTRAINT"):
                continue
            if raw.upper().startswith("PRIMARY KEY"):
                continue
            if raw.upper().startswith(")WITH") or raw.upper().startswith(") WITH"):
                continue
            if raw in {"(", ")"} or re.match(r"^\[[^\]]+\]\s+(ASC|DESC)\b", raw, re.I):
                continue
            if not COL_RE.match(raw):
                continue
            col_lines.append(parse_column(raw))
        col_lines = [c for c in col_lines if c]
        if pk:
            col_lines.append("    PRIMARY KEY (" + ", ".join(quote_ident(c) for c in pk) + ")")
        ddl = f"CREATE TABLE pangya.{quote_ident(table)} (\n" + ",\n".join(col_lines) + "\n);\n"
        out.append(ddl)
        count += 1
    return out, count


def main() -> int:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "reference/pangya-server-community/SQL/bk-schema-mssql-complet2022.sql")
    dst = Path(sys.argv[2] if len(sys.argv) > 2 else "core-db/src/main/resources/db/migration/V1__pangya_schema.sql")
    sql = read_sql(src)
    tables, n = convert_tables(sql)
    indexes = convert_indexes(sql)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(HEADER + "\n".join(tables) + "\n-- indexes\n" + "\n".join(indexes) + "\n", encoding="utf-8")
    print(f"wrote {dst} tables={n} indexes={len(indexes)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
